
openapi: 3.0.0
info:
  title: LiveApp User API
  version: 1.0.0
paths:
  /api/users/register:
    post:
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '201': { description: Registered }
  /api/users/login:
    post:
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200': { description: Token returned }
  /api/users/forget-password:
    post:
      summary: Send OTP
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
      responses:
        '200': { description: OTP sent }
  /api/users/reset-password:
    post:
      summary: Reset password with OTP
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, otp, newPassword]
              properties:
                email: { type: string }
                otp: { type: string }
                newPassword: { type: string }
      responses:
        '200': { description: Password reset success }
  /api/users/me:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200': { description: User profile }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
